name: TestDriver Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run TestDriver tests
      run: npx testdriverai@latest run testdriver/example.yaml
      env:
        TD_API_KEY: ${{ secrets.TESTDRIVER_API_KEY }}
